# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 250)
        Form.setMinimumSize(QtCore.QSize(532, 250))
        Form.setMaximumSize(QtCore.QSize(532, 250))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(532, 250))
        self.frame.setMaximumSize(QtCore.QSize(532, 250))
        self.frame.setStyleSheet("QFrame { \n"
"    color: rgb(9, 91, 255);\n"
"    background-color: rgb(9, 24, 49);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(9, 91, 255);\n"
"    border-radius: 5px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 52, 237);\n"
"    border-radius: 8px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"    border-style: solid;        \n"
"    border-width: 3px;      \n"
"    border-radius: 5px;\n"
"    border-color: rgb(202, 205, 209);\n"
"    color: rgb(87, 95, 107);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-style: solid;        \n"
"    border-width: 3px;      \n"
"    border-radius: 5px;\n"
"    border-color: rgb(202, 205, 209);\n"
"    color: rgb(87, 95, 107);\n"
"}\n"
"\n"
"QRadioButton{\n"
"    color: rgb(87, 95, 107);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 12, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userf = QtWidgets.QFrame(self.frame)
        self.userf.setMaximumSize(QtCore.QSize(16777215, 35))
        self.userf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userf.setObjectName("userf")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.userf)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.userf)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.user_l = QtWidgets.QPlainTextEdit(self.userf)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.user_l.setFont(font)
        self.user_l.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.user_l.setOverwriteMode(False)
        self.user_l.setObjectName("user_l")
        self.horizontalLayout_2.addWidget(self.user_l)
        self.verticalLayout.addWidget(self.userf)
        self.userf_2 = QtWidgets.QFrame(self.frame)
        self.userf_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.userf_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userf_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userf_2.setObjectName("userf_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.userf_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(45)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.userf_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.userf_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.userf_2)
        self.loginf = QtWidgets.QFrame(self.frame)
        self.loginf.setMaximumSize(QtCore.QSize(16777215, 100))
        self.loginf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginf.setObjectName("loginf")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.loginf)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Login_L = QtWidgets.QPushButton(self.loginf)
        self.Login_L.setObjectName("Login_L")
        self.horizontalLayout_4.addWidget(self.Login_L)
        self.SignUp_L = QtWidgets.QPushButton(self.loginf)
        self.SignUp_L.setMinimumSize(QtCore.QSize(172, 0))
        self.SignUp_L.setMaximumSize(QtCore.QSize(23232, 16777215))
        self.SignUp_L.setObjectName("SignUp_L")
        self.horizontalLayout_4.addWidget(self.SignUp_L)
        self.verticalLayout.addWidget(self.loginf, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "User Name:"))
        self.user_l.setPlaceholderText(_translate("Form", "Enter the user Name here"))
        self.label_2.setText(_translate("Form", "Pass Word:"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter The Password"))
        self.Login_L.setText(_translate("Form", "LogIn"))
        self.SignUp_L.setText(_translate("Form", "signUp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())